import type {
  User,
  Wallet,
  Transaction,
  Country,
  Carrier,
  Product,
  SalesAnalytics,
  TopProduct,
  DashboardStats,
} from './types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'admin@itu.com',
    name: 'John Admin',
    avatar: '/avatars/john.jpg',
    role: 'admin',
    phone: '+1234567890',
    rewardPoints: 1250,
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 'user-2',
    email: 'reseller@example.com',
    name: 'Jane Reseller',
    role: 'reseller',
    phone: '+1987654321',
    rewardPoints: 3500,
    createdAt: '2024-02-20T14:15:00Z',
  },
  {
    id: 'user-3',
    email: 'user@example.com',
    name: 'Bob User',
    role: 'user',
    rewardPoints: 150,
    createdAt: '2024-03-10T09:00:00Z',
  },
]

// Mock Wallets
export const mockWallets: Wallet[] = [
  {
    id: 'wallet-1',
    userId: 'user-1',
    balance: 2119.99,
    currency: 'USD',
    lastUpdated: '2024-06-15T12:00:00Z',
  },
  {
    id: 'wallet-2',
    userId: 'user-2',
    balance: 450.50,
    currency: 'USD',
    lastUpdated: '2024-06-14T18:30:00Z',
  },
]

// Mock Countries
export const mockCountries: Country[] = [
  {
    code: 'IN',
    name: 'India',
    flag: '🇮🇳',
    dialCode: '+91',
    dialingInfo: [{ prefix: '+91', minLength: 10, maxLength: 10 }],
  },
  {
    code: 'NG',
    name: 'Nigeria',
    flag: '🇳🇬',
    dialCode: '+234',
    dialingInfo: [{ prefix: '+234', minLength: 10, maxLength: 11 }],
  },
  {
    code: 'PH',
    name: 'Philippines',
    flag: '🇵🇭',
    dialCode: '+63',
    dialingInfo: [{ prefix: '+63', minLength: 10, maxLength: 10 }],
  },
  {
    code: 'MX',
    name: 'Mexico',
    flag: '🇲🇽',
    dialCode: '+52',
    dialingInfo: [{ prefix: '+52', minLength: 10, maxLength: 10 }],
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    flag: '🇧🇩',
    dialCode: '+880',
    dialingInfo: [{ prefix: '+880', minLength: 10, maxLength: 11 }],
  },
  {
    code: 'PK',
    name: 'Pakistan',
    flag: '🇵🇰',
    dialCode: '+92',
    dialingInfo: [{ prefix: '+92', minLength: 10, maxLength: 10 }],
  },
  {
    code: 'GH',
    name: 'Ghana',
    flag: '🇬🇭',
    dialCode: '+233',
    dialingInfo: [{ prefix: '+233', minLength: 9, maxLength: 10 }],
  },
  {
    code: 'KE',
    name: 'Kenya',
    flag: '🇰🇪',
    dialCode: '+254',
    dialingInfo: [{ prefix: '+254', minLength: 9, maxLength: 10 }],
  },
  {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    dialCode: '+1',
    dialingInfo: [{ prefix: '+1', minLength: 10, maxLength: 10 }],
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    dialCode: '+44',
    dialingInfo: [{ prefix: '+44', minLength: 10, maxLength: 11 }],
  },
]

// Mock Carriers
export const mockCarriers: Carrier[] = [
  // India
  {
    id: 'carrier-jio',
    code: 'JIO_IN',
    name: 'Jio',
    shortName: 'Jio',
    logo: '/carriers/jio.png',
    countryCode: 'IN',
    validationRegex: '^[6-9]\\d{9}$',
  },
  {
    id: 'carrier-airtel-in',
    code: 'AIRTEL_IN',
    name: 'Airtel India',
    shortName: 'Airtel',
    logo: '/carriers/airtel.png',
    countryCode: 'IN',
    validationRegex: '^[6-9]\\d{9}$',
  },
  {
    id: 'carrier-vi',
    code: 'VI_IN',
    name: 'Vi (Vodafone Idea)',
    shortName: 'Vi',
    logo: '/carriers/vi.png',
    countryCode: 'IN',
    validationRegex: '^[6-9]\\d{9}$',
  },
  // Nigeria
  {
    id: 'carrier-mtn-ng',
    code: 'MTN_NG',
    name: 'MTN Nigeria',
    shortName: 'MTN',
    logo: '/carriers/mtn.png',
    countryCode: 'NG',
    validationRegex: '^[0-9]{10,11}$',
  },
  {
    id: 'carrier-glo',
    code: 'GLO_NG',
    name: 'Glo Mobile',
    shortName: 'Glo',
    logo: '/carriers/glo.png',
    countryCode: 'NG',
    validationRegex: '^[0-9]{10,11}$',
  },
  {
    id: 'carrier-airtel-ng',
    code: 'AIRTEL_NG',
    name: 'Airtel Nigeria',
    shortName: 'Airtel',
    logo: '/carriers/airtel.png',
    countryCode: 'NG',
    validationRegex: '^[0-9]{10,11}$',
  },
  // Philippines
  {
    id: 'carrier-globe',
    code: 'GLOBE_PH',
    name: 'Globe Telecom',
    shortName: 'Globe',
    logo: '/carriers/globe.png',
    countryCode: 'PH',
    validationRegex: '^9\\d{9}$',
  },
  {
    id: 'carrier-smart',
    code: 'SMART_PH',
    name: 'Smart Communications',
    shortName: 'Smart',
    logo: '/carriers/smart.png',
    countryCode: 'PH',
    validationRegex: '^9\\d{9}$',
  },
  // Mexico
  {
    id: 'carrier-telcel',
    code: 'TELCEL_MX',
    name: 'Telcel',
    shortName: 'Telcel',
    logo: '/carriers/telcel.png',
    countryCode: 'MX',
    validationRegex: '^\\d{10}$',
  },
  // Ghana
  {
    id: 'carrier-mtn-gh',
    code: 'MTN_GH',
    name: 'MTN Ghana',
    shortName: 'MTN',
    logo: '/carriers/mtn.png',
    countryCode: 'GH',
  },
  // Kenya
  {
    id: 'carrier-safaricom',
    code: 'SAFARICOM_KE',
    name: 'Safaricom',
    shortName: 'Safaricom',
    logo: '/carriers/safaricom.png',
    countryCode: 'KE',
  },
  // USA
  {
    id: 'carrier-att',
    code: 'ATT_US',
    name: 'AT&T Prepaid',
    shortName: 'AT&T',
    logo: '/carriers/att.png',
    countryCode: 'US',
  },
  {
    id: 'carrier-tmobile',
    code: 'TMOBILE_US',
    name: 'T-Mobile',
    shortName: 'T-Mobile',
    logo: '/carriers/tmobile.png',
    countryCode: 'US',
  },
]

// Mock Products
export const mockProducts: Product[] = [
  // Jio Products
  {
    id: 'prod-jio-1',
    skuCode: 'JIO_IN_199',
    carrierId: 'carrier-jio',
    name: 'Jio 199 Plan',
    displayText: '2GB/day + Unlimited Calls',
    type: 'combo',
    minSendAmount: 2.50,
    maxSendAmount: 2.50,
    sendCurrency: 'USD',
    minReceiveAmount: 199,
    maxReceiveAmount: 199,
    receiveCurrency: 'INR',
    commissionRate: 3.5,
    processingMode: 'Instant',
    benefits: [
      { type: 'Data', value: 2, unit: 'GB/day' },
      { type: 'Voice', info: 'Unlimited calls' },
      { type: 'SMS', value: 100 },
    ],
    validity: '28 days',
    isPromo: false,
  },
  {
    id: 'prod-jio-2',
    skuCode: 'JIO_IN_399',
    carrierId: 'carrier-jio',
    name: 'Jio 399 Plan',
    displayText: '2.5GB/day + Unlimited Calls',
    type: 'combo',
    minSendAmount: 5.00,
    maxSendAmount: 5.00,
    sendCurrency: 'USD',
    minReceiveAmount: 399,
    maxReceiveAmount: 399,
    receiveCurrency: 'INR',
    commissionRate: 3.5,
    processingMode: 'Instant',
    benefits: [
      { type: 'Data', value: 2.5, unit: 'GB/day' },
      { type: 'Voice', info: 'Unlimited calls' },
      { type: 'SMS', value: 100 },
    ],
    validity: '56 days',
    isPromo: true,
    promoTitle: 'Extra 5GB bonus!',
    promoEndDate: '2026-05-01',
  },
  {
    id: 'prod-jio-3',
    skuCode: 'JIO_IN_666',
    carrierId: 'carrier-jio',
    name: 'Jio 666 Plan',
    displayText: '1.5GB/day + Unlimited Calls',
    type: 'combo',
    minSendAmount: 8.50,
    maxSendAmount: 8.50,
    sendCurrency: 'USD',
    minReceiveAmount: 666,
    maxReceiveAmount: 666,
    receiveCurrency: 'INR',
    commissionRate: 4.0,
    processingMode: 'Instant',
    benefits: [
      { type: 'Data', value: 1.5, unit: 'GB/day' },
      { type: 'Voice', info: 'Unlimited calls' },
      { type: 'SMS', value: 100 },
    ],
    validity: '84 days',
  },
  // Airtel India Products
  {
    id: 'prod-airtel-in-1',
    skuCode: 'AIRTEL_IN_179',
    carrierId: 'carrier-airtel-in',
    name: 'Airtel 179 Plan',
    displayText: '2GB/day + Unlimited Calls',
    type: 'combo',
    minSendAmount: 2.25,
    maxSendAmount: 2.25,
    sendCurrency: 'USD',
    minReceiveAmount: 179,
    maxReceiveAmount: 179,
    receiveCurrency: 'INR',
    commissionRate: 3.0,
    processingMode: 'Instant',
    benefits: [
      { type: 'Data', value: 2, unit: 'GB/day' },
      { type: 'Voice', info: 'Unlimited calls' },
    ],
    validity: '28 days',
  },
  {
    id: 'prod-airtel-in-2',
    skuCode: 'AIRTEL_IN_455',
    carrierId: 'carrier-airtel-in',
    name: 'Airtel 455 Plan',
    displayText: '1GB/day + Unlimited Calls',
    type: 'combo',
    minSendAmount: 5.75,
    maxSendAmount: 5.75,
    sendCurrency: 'USD',
    minReceiveAmount: 455,
    maxReceiveAmount: 455,
    receiveCurrency: 'INR',
    commissionRate: 3.5,
    processingMode: 'Instant',
    benefits: [
      { type: 'Data', value: 1, unit: 'GB/day' },
      { type: 'Voice', info: 'Unlimited calls' },
    ],
    validity: '84 days',
  },
  // MTN Nigeria Products
  {
    id: 'prod-mtn-1',
    skuCode: 'MTN_NG_500',
    carrierId: 'carrier-mtn-ng',
    name: 'MTN N500 Airtime',
    displayText: 'N500 Airtime Top-up',
    type: 'voice',
    minSendAmount: 1.25,
    maxSendAmount: 1.25,
    sendCurrency: 'USD',
    minReceiveAmount: 500,
    maxReceiveAmount: 500,
    receiveCurrency: 'NGN',
    commissionRate: 4.0,
    processingMode: 'Instant',
    benefits: [{ type: 'Airtime', value: 500, unit: 'NGN' }],
  },
  {
    id: 'prod-mtn-2',
    skuCode: 'MTN_NG_1000',
    carrierId: 'carrier-mtn-ng',
    name: 'MTN N1000 Airtime',
    displayText: 'N1000 Airtime Top-up',
    type: 'voice',
    minSendAmount: 2.50,
    maxSendAmount: 2.50,
    sendCurrency: 'USD',
    minReceiveAmount: 1000,
    maxReceiveAmount: 1000,
    receiveCurrency: 'NGN',
    commissionRate: 4.5,
    processingMode: 'Instant',
    benefits: [{ type: 'Airtime', value: 1000, unit: 'NGN' }],
  },
  {
    id: 'prod-mtn-3',
    skuCode: 'MTN_NG_DATA_1GB',
    carrierId: 'carrier-mtn-ng',
    name: 'MTN 1GB Data',
    displayText: '1GB Data Bundle - 30 days',
    type: 'data',
    minSendAmount: 2.00,
    maxSendAmount: 2.00,
    sendCurrency: 'USD',
    minReceiveAmount: 1000,
    maxReceiveAmount: 1000,
    receiveCurrency: 'NGN',
    commissionRate: 5.0,
    processingMode: 'Instant',
    benefits: [{ type: 'Data', value: 1, unit: 'GB' }],
    validity: '30 days',
  },
  // Globe Philippines Products
  {
    id: 'prod-globe-1',
    skuCode: 'GLOBE_PH_100',
    carrierId: 'carrier-globe',
    name: 'Globe P100 Load',
    displayText: 'P100 Regular Load',
    type: 'combo',
    minSendAmount: 2.00,
    maxSendAmount: 2.00,
    sendCurrency: 'USD',
    minReceiveAmount: 100,
    maxReceiveAmount: 100,
    receiveCurrency: 'PHP',
    commissionRate: 3.0,
    processingMode: 'Instant',
    benefits: [{ type: 'Load', value: 100, unit: 'PHP' }],
  },
  {
    id: 'prod-globe-2',
    skuCode: 'GLOBE_PH_300',
    carrierId: 'carrier-globe',
    name: 'Globe P300 Load',
    displayText: 'P300 Regular Load',
    type: 'combo',
    minSendAmount: 6.00,
    maxSendAmount: 6.00,
    sendCurrency: 'USD',
    minReceiveAmount: 300,
    maxReceiveAmount: 300,
    receiveCurrency: 'PHP',
    commissionRate: 3.5,
    processingMode: 'Instant',
    benefits: [{ type: 'Load', value: 300, unit: 'PHP' }],
    isPromo: true,
    promoTitle: 'Get 50MB bonus data!',
    promoEndDate: '2026-04-30',
  },
  // Telcel Mexico Products
  {
    id: 'prod-telcel-1',
    skuCode: 'TELCEL_MX_100',
    carrierId: 'carrier-telcel',
    name: 'Telcel $100 MXN',
    displayText: '$100 MXN Recarga',
    type: 'combo',
    minSendAmount: 5.50,
    maxSendAmount: 5.50,
    sendCurrency: 'USD',
    minReceiveAmount: 100,
    maxReceiveAmount: 100,
    receiveCurrency: 'MXN',
    commissionRate: 3.0,
    processingMode: 'Instant',
    benefits: [{ type: 'Load', value: 100, unit: 'MXN' }],
  },
  {
    id: 'prod-telcel-2',
    skuCode: 'TELCEL_MX_200',
    carrierId: 'carrier-telcel',
    name: 'Telcel $200 MXN',
    displayText: '$200 MXN Recarga',
    type: 'combo',
    minSendAmount: 11.00,
    maxSendAmount: 11.00,
    sendCurrency: 'USD',
    minReceiveAmount: 200,
    maxReceiveAmount: 200,
    receiveCurrency: 'MXN',
    commissionRate: 3.5,
    processingMode: 'Instant',
    benefits: [{ type: 'Load', value: 200, unit: 'MXN' }],
  },
]

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: 'txn-1',
    userId: 'user-1',
    type: 'recharge',
    amount: 5.00,
    currency: 'USD',
    status: 'completed',
    description: 'Jio Recharge - +91 9876543210',
    rewardPoints: 5,
    createdAt: '2024-06-15T10:30:00Z',
    metadata: {
      phoneNumber: '+919876543210',
      carrier: 'JIO_IN',
      carrierName: 'Jio',
      country: 'IN',
      countryName: 'India',
      productName: 'Jio 399 Plan',
      skuCode: 'JIO_IN_399',
    },
  },
  {
    id: 'txn-2',
    userId: 'user-1',
    type: 'recharge',
    amount: 2.50,
    currency: 'USD',
    status: 'completed',
    description: 'MTN Recharge - +234 8012345678',
    rewardPoints: 2,
    createdAt: '2024-06-14T15:45:00Z',
    metadata: {
      phoneNumber: '+2348012345678',
      carrier: 'MTN_NG',
      carrierName: 'MTN Nigeria',
      country: 'NG',
      countryName: 'Nigeria',
      productName: 'MTN N1000 Airtime',
      skuCode: 'MTN_NG_1000',
    },
  },
  {
    id: 'txn-3',
    userId: 'user-1',
    type: 'topup',
    amount: 100.00,
    currency: 'USD',
    status: 'completed',
    description: 'Wallet Top-up via Card',
    createdAt: '2024-06-13T09:00:00Z',
  },
  {
    id: 'txn-4',
    userId: 'user-1',
    type: 'recharge',
    amount: 6.00,
    currency: 'USD',
    status: 'completed',
    description: 'Globe Recharge - +63 9171234567',
    rewardPoints: 6,
    createdAt: '2024-06-12T11:20:00Z',
    metadata: {
      phoneNumber: '+639171234567',
      carrier: 'GLOBE_PH',
      carrierName: 'Globe Telecom',
      country: 'PH',
      countryName: 'Philippines',
      productName: 'Globe P300 Load',
      skuCode: 'GLOBE_PH_300',
    },
  },
  {
    id: 'txn-5',
    userId: 'user-1',
    type: 'recharge',
    amount: 11.00,
    currency: 'USD',
    status: 'failed',
    description: 'Telcel Recharge - +52 5512345678',
    createdAt: '2024-06-11T16:30:00Z',
    metadata: {
      phoneNumber: '+525512345678',
      carrier: 'TELCEL_MX',
      carrierName: 'Telcel',
      country: 'MX',
      countryName: 'Mexico',
      productName: 'Telcel $200 MXN',
      skuCode: 'TELCEL_MX_200',
    },
  },
  {
    id: 'txn-6',
    userId: 'user-1',
    type: 'refund',
    amount: 11.00,
    currency: 'USD',
    status: 'completed',
    description: 'Refund for failed Telcel recharge',
    createdAt: '2024-06-11T17:00:00Z',
  },
  {
    id: 'txn-7',
    userId: 'user-1',
    type: 'points_earned',
    amount: 25,
    currency: 'PTS',
    status: 'completed',
    description: 'Reward points for 5 successful recharges',
    rewardPoints: 25,
    createdAt: '2024-06-10T12:00:00Z',
  },
]

// Mock Sales Analytics
export const mockSalesAnalytics: SalesAnalytics[] = [
  { date: 'Jan', revenue: 2800, orders: 120, previousYearRevenue: 2400 },
  { date: 'Feb', revenue: 3200, orders: 145, previousYearRevenue: 2800 },
  { date: 'Mar', revenue: 3800, orders: 168, previousYearRevenue: 3200 },
  { date: 'Apr', revenue: 4200, orders: 190, previousYearRevenue: 3600 },
  { date: 'May', revenue: 5800, orders: 220, previousYearRevenue: 4200 },
  { date: 'Jun', revenue: 9427.64, orders: 280, previousYearRevenue: 1427.64 },
  { date: 'Jul', revenue: 6200, orders: 240, previousYearRevenue: 5200 },
  { date: 'Aug', revenue: 5800, orders: 210, previousYearRevenue: 4800 },
  { date: 'Sep', revenue: 6400, orders: 250, previousYearRevenue: 5400 },
  { date: 'Oct', revenue: 7200, orders: 290, previousYearRevenue: 6000 },
  { date: 'Nov', revenue: 8400, orders: 340, previousYearRevenue: 7200 },
  { date: 'Dec', revenue: 9800, orders: 380, previousYearRevenue: 8400 },
]

// Mock Top Products
export const mockTopProducts: TopProduct[] = [
  {
    id: 'prod-jio-2',
    name: 'Jio 399 Plan',
    price: 5.00,
    sold: 444,
    image: '/products/jio.png',
  },
  {
    id: 'prod-mtn-2',
    name: 'MTN N1000 Airtime',
    price: 2.50,
    sold: 173,
    image: '/products/mtn.png',
  },
  {
    id: 'prod-globe-2',
    name: 'Globe P300 Load',
    price: 6.00,
    sold: 88,
    image: '/products/globe.png',
  },
  {
    id: 'prod-telcel-1',
    name: 'Telcel $100 MXN',
    price: 5.50,
    sold: 233,
    image: '/products/telcel.png',
  },
]

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalRevenue: 9427.64,
  totalOrders: 57922,
  revenueChange: 10,
  ordersChange: -15,
  monthlyRevenue: 1779.44,
  yearlyRevenue: 5640.51,
  monthlyChange: 187,
  yearlyChange: 553,
}

// Mock Recharge Orders (for admin)
export const mockRechargeOrders = [
  {
    id: 'order-001',
    userId: 'user-3',
    countryCode: '+91',
    countryName: 'India',
    phoneNumber: '9876543210',
    providerCode: 'JIO',
    providerName: 'Jio',
    productId: 'prod-jio-1',
    productName: '2GB Daily Pack',
    senderAmount: 15.00,
    senderCurrency: 'USD',
    destinationAmount: 599,
    destinationCurrency: 'INR',
    status: 'completed',
    paymentMethod: 'card',
    createdAt: '2024-06-04T10:30:00Z',
    completedAt: '2024-06-04T10:30:45Z',
  },
  {
    id: 'order-002',
    userId: 'user-3',
    countryCode: '+234',
    countryName: 'Nigeria',
    phoneNumber: '8012345678',
    providerCode: 'MTN',
    providerName: 'MTN Nigeria',
    productId: 'prod-mtn-1',
    productName: 'N1000 Airtime',
    senderAmount: 6.00,
    senderCurrency: 'USD',
    destinationAmount: 1000,
    destinationCurrency: 'NGN',
    status: 'completed',
    paymentMethod: 'wallet',
    createdAt: '2024-06-19T14:15:00Z',
    completedAt: '2024-06-19T14:15:30Z',
  },
  {
    id: 'order-003',
    userId: 'user-2',
    countryCode: '+63',
    countryName: 'Philippines',
    phoneNumber: '9171234567',
    providerCode: 'GLOBE',
    providerName: 'Globe',
    productId: 'prod-globe-1',
    productName: 'Globe P500 Load',
    senderAmount: 10.00,
    senderCurrency: 'USD',
    destinationAmount: 500,
    destinationCurrency: 'PHP',
    status: 'failed',
    paymentMethod: 'card',
    errorMessage: 'Provider temporarily unavailable',
    createdAt: '2024-06-25T09:45:00Z',
  },
  {
    id: 'order-004',
    userId: 'user-3',
    countryCode: '+1',
    countryName: 'United States',
    phoneNumber: '5551234567',
    providerCode: 'ATT',
    providerName: 'AT&T',
    productId: 'prod-att-1',
    productName: '$25 Prepaid',
    senderAmount: 25.00,
    senderCurrency: 'USD',
    destinationAmount: 25,
    destinationCurrency: 'USD',
    status: 'processing',
    paymentMethod: 'card',
    createdAt: '2024-07-03T16:20:00Z',
  },
  {
    id: 'order-005',
    userId: 'user-2',
    countryCode: '+91',
    countryName: 'India',
    phoneNumber: '9123456789',
    providerCode: 'AIRTEL',
    providerName: 'Airtel India',
    productId: 'prod-airtel-1',
    productName: 'Unlimited Calls + 2GB',
    senderAmount: 12.00,
    senderCurrency: 'USD',
    destinationAmount: 499,
    destinationCurrency: 'INR',
    status: 'completed',
    paymentMethod: 'wallet',
    createdAt: '2024-07-10T11:00:00Z',
    completedAt: '2024-07-10T11:00:25Z',
  },
  {
    id: 'order-006',
    userId: 'user-3',
    countryCode: '+52',
    countryName: 'Mexico',
    phoneNumber: '5512345678',
    providerCode: 'TELCEL',
    providerName: 'Telcel',
    productId: 'prod-telcel-1',
    productName: 'Telcel $200 MXN',
    senderAmount: 11.50,
    senderCurrency: 'USD',
    destinationAmount: 200,
    destinationCurrency: 'MXN',
    status: 'refunded',
    paymentMethod: 'card',
    createdAt: '2024-07-15T08:30:00Z',
    refundedAt: '2024-07-15T12:00:00Z',
  },
]
